
version: "3.9"

services:
  queries_challenge: 
    image: postgres
    container_name: queries_challenge
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: desafio3
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - queries_challenge
    depends_on:
      - queries_challenge

volumes:
  pgdata:
    driver: local
